-- MySQL Script generated by MySQL Workbench
-- Wed Jun 19 20:04:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `id_uf` INT NOT NULL,
  `sigla_uf` VARCHAR(45) NULL,
  `nome_uf` VARCHAR(45) NULL,
  PRIMARY KEY (`id_uf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `id_cidade` INT NOT NULL,
  `nome_cidade` VARCHAR(45) NULL,
  `id_uf` INT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_uf_idx` (`id_uf` ASC) VISIBLE,
  CONSTRAINT `fk_uf`
    FOREIGN KEY (`id_uf`)
    REFERENCES `mydb`.`UF` (`id_uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `id_pessoa` INT NOT NULL,
  `nome_pessoa` VARCHAR(45) NULL,
  `apelido` VARCHAR(45) NULL,
  `dt_nascimento` DATETIME NULL,
  `id_cidade_gosta` INT NULL,
  `id_cidade_odeia` INT NULL,
  `id_cidade_mora` INT NULL,
  `Pessoacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pessoa`),
  INDEX `fk_cidade_gosta_idx` (`id_cidade_gosta` ASC) VISIBLE,
  INDEX `fk_cidade_odeia_idx` (`id_cidade_odeia` ASC) VISIBLE,
  INDEX `fk_cidade_mora_idx` (`id_cidade_mora` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_gosta`
    FOREIGN KEY (`id_cidade_gosta`)
    REFERENCES `mydb`.`Cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cidade_odeia`
    FOREIGN KEY (`id_cidade_odeia`)
    REFERENCES `mydb`.`Cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cidade_mora`
    FOREIGN KEY (`id_cidade_mora`)
    REFERENCES `mydb`.`Cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filiacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Filiacao` (
  `id_filho` INT NOT NULL,
  `id_pai` INT NOT NULL,
  PRIMARY KEY (`id_filho`, `id_pai`),
  INDEX `fk_filiacao_idx` (`id_pai` ASC) VISIBLE,
  CONSTRAINT `fk_filho`
    FOREIGN KEY (`id_filho`)
    REFERENCES `mydb`.`Pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pai`
    FOREIGN KEY (`id_pai`)
    REFERENCES `mydb`.`Pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prato` (
  `id_prato` INT NOT NULL,
  `nome_prato` VARCHAR(45) NULL,
  `id_receita` INT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_prato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaGostaPrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaGostaPrato` (
  `id_pessoa` INT NOT NULL,
  `id_prato` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`, `id_prato`),
  INDEX `fk_prato_idx` (`id_prato` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`Pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prato`
    FOREIGN KEY (`id_prato`)
    REFERENCES `mydb`.`Prato` (`id_prato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Receita` (
  `id_receita` INT NOT NULL,
  `id_prato` INT NULL,
  PRIMARY KEY (`id_receita`),
  INDEX `fk_receita_idx` (`id_prato` ASC) VISIBLE,
  CONSTRAINT `fk_receita`
    FOREIGN KEY (`id_prato`)
    REFERENCES `mydb`.`Prato` (`id_prato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingrediente` (
  `id_ingrediente` INT NOT NULL,
  `nome_ingrediente` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ingrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passo` (
  `id_passo` INT NOT NULL,
  `verbo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_passo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UnidadeMedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UnidadeMedida` (
  `nome_medida` VARCHAR(45) NULL,
  `id_unidade_medida` INT NOT NULL,
  PRIMARY KEY (`id_unidade_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utensilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utensilio` (
  `id_utensilio` INT NOT NULL,
  `nome_utensilio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_utensilio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AcaoEspecifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AcaoEspecifica` (
  `id_passo` INT NOT NULL,
  `id_ingrediente` INT NOT NULL,
  `quantidade` INT NULL,
  `id_unidade_medida` INT NULL,
  `tempo_minutos` INT NULL,
  `id_utensilio` INT NULL,
  PRIMARY KEY (`id_passo`, `id_ingrediente`),
  INDEX `fk_unidade_medida_idx` (`id_unidade_medida` ASC) VISIBLE,
  INDEX `fk_ingrediente_idx` (`id_ingrediente` ASC) VISIBLE,
  INDEX `fk_utensilio_idx` (`id_utensilio` ASC) VISIBLE,
  CONSTRAINT `fk_passo`
    FOREIGN KEY (`id_passo`)
    REFERENCES `mydb`.`Passo` (`id_passo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingrediente`
    FOREIGN KEY (`id_ingrediente`)
    REFERENCES `mydb`.`Ingrediente` (`id_ingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidade_medida`
    FOREIGN KEY (`id_unidade_medida`)
    REFERENCES `mydb`.`UnidadeMedida` (`id_unidade_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utensilio`
    FOREIGN KEY (`id_utensilio`)
    REFERENCES `mydb`.`Utensilio` (`id_utensilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PassoDaReceita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PassoDaReceita` (
  `id_passo` INT NOT NULL,
  `id_receita` INT NOT NULL,
  PRIMARY KEY (`id_passo`, `id_receita`),
  INDEX `id_receita_idx` (`id_receita` ASC) VISIBLE,
  CONSTRAINT `fk_id_passo`
    FOREIGN KEY (`id_passo`)
    REFERENCES `mydb`.`Passo` (`id_passo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_receita`
    FOREIGN KEY (`id_receita`)
    REFERENCES `mydb`.`Receita` (`id_receita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
